repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.2
    hooks:
      - id: clang-format
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
    - id: cmake-format
    - id: cmake-lint
